networks:
  ollama-network:
    driver: bridge

services:
  # Ollama
  ollama:
    volumes:
      - ./Volume/Ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: all
              capabilities:
                - gpu
    ports:
      - 11434:11434
    networks:
      - ollama-network
      
  # WebUI
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./Volume/open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 4242:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
 #     - WEBUI_SECRET_KEY=${WEBUI_PASSWORD}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-network

  # PostgreSQL (PGVector)
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    volumes:
      - ./Volume/pgvector:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    networks:
      - ollama-network